### ISSUE TITLE
Portuguese month/day ordering bug

### ISSUE THREAD

**Issue by ottumm** [scrapinghub/dateparser#658]
There is a bug with Portuguese dates where dateparser switches the month and day ordering. This regression occurred sometime between v0.6.0 and v0.7.0.

Example text is "segunda 10-02-2015 4:06am", which should parse to "2015-02-10" but currently parses to "2015-10-02".

I've created PR #438 to add a unit test that exposes this regression: https://github.com/scrapinghub/dateparser/pull/438/files#diff-36128d81467a740315c9e5f49860c291

Based on my git-bisect testing, it looks like 8c24e3a is the first commit to break this. Or, at least, the first commit where import dateparser works successfully and the test is broken.

**Comment by harsh9200** [comment]
The current master gives the correct month and day.
```
>>> dateparser.parse('segunda 10-02-2015 4:06am').strftime('%a %Y-%m-%d')
'Tue 2015-02-10'
```
I think this bug is fixed. 

Can you please check? @ottumm

**Comment by noviluni** [comment]
Hi @ottumm 

I've trying to reproduce it with different versions (even master) and I always get the correct result (and the test you added in the PR passes). 

I will close this issue. If your problem is not solved or there is something we missed please, don't hesitate to re-open this ticket.

**Comment by ottumm** [comment]
Thanks @noviluni! I agree with the closure.
