### ISSUE TITLE
Improve the `search_dates` section in the docs

### ISSUE THREAD

**Issue by noviluni** [scrapinghub/dateparser#737]
raised from https://github.com/scrapinghub/dateparser/issues/397

**Comment by noviluni** [comment]
Related issue: https://github.com/scrapinghub/dateparser/issues/442

**Comment by gavishpoddar** [comment]
Hi @noviluni, please check it seems the issue is fixed with #779 which is merged and issue #397 is also closed.

**Comment by Gallaecio** [comment]
#397 was closed precisely because this ticket was created for this work, not because this work was done. https://github.com/scrapinghub/dateparser/pull/779 did not alter the documentation of `search_dates` in any way.

While I’m not sure what work is required, as [I’ve said in the past](https://github.com/scrapinghub/dateparser/issues/397#issuecomment-565412905), I believe the issue is still as relevant as it was in #397.
